spring.application.name=weatherAPI
weather_api=${API_KEY}
logging.level.redis.clients.jedis=TRACE
logging.level.org.springframework.data.redis=TRACE
logging.level.org.springframework.cache=TRACE
logging.level.org.springframework.data.redis.connection=TRACE
